### ISSUE TITLE
extend-expect can't be seen by TypeScript ESM modules

### ISSUE THREAD

**Issue by jgoux** [crutchcorn/cli-testing-library#17]
- `cli-testing-library` version: 1.0.2
- Testing Framework and version: vitest@0.13.0
  
- DOM Environment:
  

### What you did:

I tried to register the custom matcher with Vitest.

### What happened:

The statement `import "cli-testing-library/extend-expect"` isn't pointing to anything when my own package is of type `"type": "module"`.

### Suggested solution:

You need to use an `exports` map to describe how your package is consumed in the `package.json`
```json
"exports": {
    ".": {
      "types": "./types/index.d.ts",
      "require": "./dist/cli-testing-library.cjs.js",
      "import": "./dist/cli-testing-library.esm.js"
    },
    "./extend-expect": {
      "types": "./extend-expect.d.ts",
      "require": "./dist/extend-expect.js",
      "import": "./dist/extend-expect.js"
    }
  },
```

**Comment by crutchcorn** [comment]
Do you want to make a PR with the suggested changes?

I can release it alongside the changes in #16 today :)
