### ISSUE TITLE
Watch mode testing

### ISSUE THREAD

**Issue by mrazauskas** [crutchcorn/cli-testing-library#27]
### Describe the feature you'd like:

Really happy to find this library. I am looking around for a user centric of testing a CLI of a test runner. I have read documentation a couple of times. It seems like most of the patterns covered look like this: user must see this prompt, be able to interact with it, and the library has assertions to check the output after interaction.

That’s all very useful. What I try to understand is the following: a test runner is watching the file system, user is changing files, and the runner is responding to that. In this case there are no prompts, but user still sees the output which was triggered by some activity not directly related with the CLI app.

### Suggested implementation:

I wonder if the `cli-testing-library` is interested to cover this use case? What would be the best practises in this case?

### Describe alternatives you've considered:

Own code. Own approach.

### Teachability, Documentation, Adoption, Migration Strategy:

Users will be able to use the `cli-testing-library` to test watch mode of their apps.

**Comment by mrazauskas** [comment]
I guess, that is not planned. Feel free to reopen.

**Comment by crutchcorn** [comment]
This issue _not planned_, but closing issues like this without maintainer feedback just hides issues like this from me to evaluate and comes across as snarky.

The reason this issue is not planned is that a watch mode is a feature from test runners, which is not in this library's purview

**Comment by mrazauskas** [comment]
You had plenty of time to evaluate before I closed the issue. That was the whole 14 days. Keeping silence for this long time indicates low interest to evaluate or low capacity or something else. I do not agree that I was hiding something from you.

**Comment by crutchcorn** [comment]
> You had plenty of time to evaluate before I closed the issue. That was the whole 14 days. 

LOL. LMAO, even.
