### ISSUE TITLE
fireEvent.sigkill fails on some CI systems

### ISSUE THREAD

**Issue by crutchcorn** [crutchcorn/cli-testing-library#3]
While this code runs on all the same versions of Node on Windows within CI, it seems to error out on platforms like Windows.

Log:

https://github.com/crutchcorn/cli-testing-library/runs/4339953929?check_suite_focus=true

It appears to be a permissions issue of being unable to `taskkill` (or similar) a PID on Windows machines on GH Actions CI. This makes sense to me, as it may introduce vulnerabilities. 

As a temporary workaround, I will be removing that test from CI and simply doing tests manually on Windows myself. Please let us know if there's a better way you know of

**Comment by crutchcorn** [comment]
OK I'm stumped. I've tried for hours and hours now with no avail. It seems to work fine in CircleCI, but not GitHub actions.

I'm going to mark this as "help needed" and hope the ecosystem has some kind of solution

Note: This library works fine for Windows itself. I will be manually testing everything on my machine to make sure it works and continue to write Windows-specific tests

**Comment by crutchcorn** [comment]
OK it's not just `sigkill` and it's not just Windows

https://github.com/crutchcorn/cli-testing-library/actions/runs/1558975085

There is some timing issue somewhere, and I don't _think_ it's our code, but I could be wrong.

**Comment by crutchcorn** [comment]
We're running into this issue again in Plop as Windows devices are failing again.

I'm willing to pay a bounty of $50 if anyone is able to solve these issues well enough that Windows CI systems do not fail on GitHub actions on the Plop monorepo 5x in a row.

**Comment by smartbizlord** [comment]
attempt #3

**Comment by Drex72** [comment]
> OK I'm stumped. I've tried for hours and hours now with no avail. It seems to work fine in CircleCI, but not GitHub actions.
> 
> I'm going to mark this as "help needed" and hope the ecosystem has some kind of solution
> 
> Note: This library works fine for Windows itself. I will be manually testing everything on my machine to make sure it works and continue to write Windows-specific tests

Hey @crutchcorn  Is it possible for me to get the config that you used for circle ci?

**Comment by crutchcorn** [comment]
@Drex72 it might be in the commit history. Otherwise I wouldn't know where it is :( Sorry I'm not more help

**Comment by Drex72** [comment]
> @Drex72 it might be in the commit history. Otherwise I wouldn't know where it is :( Sorry I'm not more help

Alright, no problem
that's cool
i'd check for it
i cant see the logs because it says it doesnt exist so i want to create a repro :)

**Comment by LayZeeDK** [comment]
Failing job in Plop

**Comment by LayZeeDK** [comment]
Failing job in Plop
https://github.com/plopjs/plop/actions/runs/7304409077/job/19906537229

**Comment by LayZeeDK** [comment]
Where's the source code in CLI Testing Library that runs a `taskkill` command on Windows?

**Comment by Waldeedle** [comment]
@crutchcorn just want to be clear, you are not seeing this issue for yourself locally? I was able to reproduce it on my local windows 11 desktop

**Comment by crutchcorn** [comment]
@Waldeedle INTERESTING. I, in fact, was not able to reproduce it locally even recently on the Plop repo.

**Comment by Waldeedle** [comment]
@crutchcorn try cloning the repo to a new folder and just run the exact commands from your test workflow:
I think your hunch is right, I wonder if turbo is not handling child processes correctly because I can only reproduce it on the initial clone of the repo, any subsequent run just works.

Here's some copy-pasta for your convenience
```bash
git clone git@github.com:plopjs/plop.git
cd plop/
yarn install --frozen-lockfile
yarn test
```

**Comment by crutchcorn** [comment]
@Waldeedle it's interesting it mentions Microsoft AV. What if you turn it off (temporarily) for running? [Only if you trust it, feel free to read the source]

I have mine disabled in favor of a different antivirus and maybe that could be part of the root.

**Comment by Waldeedle** [comment]
@crutchcorn assuming you meant from my screenshot? Sorry should've clarified that this was from my task manager, its going to show all processes, I will switch over to process explorer so I can see the related processes from the test

**Comment by Waldeedle** [comment]
/attempt #3
I see where it is erroring out, and believe I have a potential solution. 
Before I create a PR, could I get context around, this particular if statement, why are you attempting to kill a process that has already exited/doesn't exist?
```javascript
if (err.message.includes('could not be terminated') && err.message.includes('There is no running instance of the task.'))
```

**Comment by crutchcorn** [comment]
> I see where it is erroring out, and believe I have a potential solution. 
> Before I create a PR, could I get context around, this particular if statement, why are you attempting to kill a process that has already exited/doesn't exist?
> ```javascript
> if (err.message.includes('could not be terminated') && err.message.includes('There is no running instance of the task.'))
> ```
> 

Truthfully I don't remember. I think this was an attempt to fix the problem at hand or work around windows specifically but idk

**Comment by crutchcorn** [comment]
@Waldeedle thanks so much for contributing to this project and helping us out! Great work!

**Comment by Waldeedle** [comment]
@crutchcorn anytime, thanks for the brain teaser! 👏
